//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceAdjustment.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string APP_CODE {
            get {
                return ((string)(this["APP_CODE"]));
            }
            set {
                this["APP_CODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string APP_AUTH {
            get {
                return ((string)(this["APP_AUTH"]));
            }
            set {
                this["APP_AUTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DB_SC_PATH {
            get {
                return ((string)(this["DB_SC_PATH"]));
            }
            set {
                this["DB_SC_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DB_DYH_PATH {
            get {
                return ((string)(this["DB_DYH_PATH"]));
            }
            set {
                this["DB_DYH_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lyc2010")]
        public string DB_SC_PWD {
            get {
                return ((string)(this["DB_SC_PWD"]));
            }
            set {
                this["DB_SC_PWD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sdkdchkj")]
        public string DB_DYH_UID {
            get {
                return ((string)(this["DB_DYH_UID"]));
            }
            set {
                this["DB_DYH_UID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S2D0C0H6")]
        public string DB_DYH_PWD {
            get {
                return ((string)(this["DB_DYH_PWD"]));
            }
            set {
                this["DB_DYH_PWD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DB_TARGET_PATH {
            get {
                return ((string)(this["DB_TARGET_PATH"]));
            }
            set {
                this["DB_TARGET_PATH"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0; Data Source={0}; Jet OLEDB:System Database={1};" +
            " User Id={2}; Password={3}")]
        public string DB_DYH_STR {
            get {
                return ((string)(this["DB_DYH_STR"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0; Data Source={0}; Jet OLEDB:Database Password={1" +
            "}")]
        public string DB_SC_STR {
            get {
                return ((string)(this["DB_SC_STR"]));
            }
            set {
                this["DB_SC_STR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.18")]
        public decimal SC_PRICE_OLD {
            get {
                return ((decimal)(this["SC_PRICE_OLD"]));
            }
            set {
                this["SC_PRICE_OLD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6102")]
        public decimal DYH_PRICE_NEW {
            get {
                return ((decimal)(this["DYH_PRICE_NEW"]));
            }
            set {
                this["DYH_PRICE_NEW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6102")]
        public decimal SC_PRICE_NEW {
            get {
                return ((decimal)(this["SC_PRICE_NEW"]));
            }
            set {
                this["SC_PRICE_NEW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DB_DYH_MDW {
            get {
                return ((string)(this["DB_DYH_MDW"]));
            }
            set {
                this["DB_DYH_MDW"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("操作流程：\r\n  1. 选取修改后的数据文件保存地址，修改后的MDB文件保存在此\r\n  2. 多用户配置：\r\n      1）选择对应MDB MDW文件\r\n   " +
            "   2）配置价格\r\n      3）选择是否删除指定日期前数据\r\n  3.商场配置\r\n      1）选择MDB文件\r\n      2）配置价格\r\n     " +
            " 3）选择是否删除指定日期前数据\r\n  4.按【执行】按钮，结果看提示")]
        public string Help {
            get {
                return ((string)(this["Help"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PRICE_DATA {
            get {
                return ((string)(this["PRICE_DATA"]));
            }
            set {
                this["PRICE_DATA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DB_TARGET_PATH_DYH {
            get {
                return ((string)(this["DB_TARGET_PATH_DYH"]));
            }
            set {
                this["DB_TARGET_PATH_DYH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DB_TARGET_PATH_SC {
            get {
                return ((string)(this["DB_TARGET_PATH_SC"]));
            }
            set {
                this["DB_TARGET_PATH_SC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoRun {
            get {
                return ((bool)(this["AutoRun"]));
            }
            set {
                this["AutoRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoExit {
            get {
                return ((bool)(this["AutoExit"]));
            }
            set {
                this["AutoExit"] = value;
            }
        }
    }
}
